### PR TITLE
simplify & close file handler

### PR DESCRIPTION
**Pull request by lewgun**

### CODE REVIEW

**Comment by chrislusf** [comment]
I do not found shortening the variable names helpful. They are additional "overhead" when trying to understand the code.

**Comment by lewgun** [comment]
英文太差，如你在知乎上所说github上交流也比较麻烦，所以在此我用中文表达下我的看法，怕英文说不清楚，在这个及以前的pr中，我基于了以下一些原则对一些变量名进行了简化
1. 代码中有的地方你使用了execStatus,有的地方使用了executionStatus,我将他们统一到了execStatus
2. 有些名字是go代码中约定俗成的，比如request/response -> req/resp
3.有的函数本身比较短小，比如withClient中的grpcConection这个变量，在此处，此变量名的长度相对于此函数的体量，感觉有点臃肿
4.在有些方法中，比如translateToStepGroups这个方法中，foundStepId/hasParentIdId这两个bool标示，只是用以判定是否找到，而找的内容，从findAncestorStepId这个函数名可以得到，同时基于"comma,ok",惯用法，此处更详细的foundStepId/hasParentIdId，个人觉得，除开让代码数变多之外，可能没有达到你想要的效果，以我这几天阅读gleam的经验，很多新知识，术语，因为暂时注释的缺失，只能通过代码去推，而看到密密麻麻的代码，让人有一种很压抑的感觉

**Comment by chrislusf** [comment]
I am from Java camp, and find the full name is better to denote the meaning and variable types.

Smaller number of lines is dense, but you can have better understanding of the code framework. I usually want to put one line of logic into one line, without wraps if the IDE or readability allows.

**Comment by chrislusf** [comment]
need your email to send the invites.

**Comment by lewgun** [comment]
tempvar$163$com

**Comment by lewgun** [comment]
i had reverted the prev pr, and just fix the bug & change something which does not match the coding style

**Pull request merged**
