### PR TITLE
Support gzip and bzip2 for sequential file readers

### PR DESCRIPTION
**Pull request by svmhdvn**
Small convenience for gzip and bzip2 files containing lines of sequential row data.

### CODE REVIEW

**Comment by chrislusf** [comment]
gzip is a compression algorithm, not a particular format.

How about just determining whether it is gzip by checking the FileName from FileShardInfo?

**Comment by svmhdvn** [comment]
Sounds good, I'll fix up my PR by tomorrow with that. Just made this quick change locally for my convenience and thought this might be useful.

**Comment by svmhdvn** [comment]
Fixed, let me know if you need any other changes.

**Comment by chrislusf** [comment]
thanks!

**Pull request merged**
